@startuml

class Decimal
Decimal <-[dashed]- CurrencyCalculator
Decimal <-[dashed]- Currency
Decimal <-u[dashed]- NBPParser

class xml
xml <-d[dashed]- XMLProvider

class Currency {
    + code: str <<get>>
    + name: str <<get>>
    + avg_exchange_rate: Decimal <<get>>
    + conversion_factor: int <<get>>
}

class Currencies {
    + currencies: [Currency] <<get>>
    + get_currencies_dict(): {str: Currency}}
}
Currencies *-- "n" Currency


class SingletonMetaclass {
    - _instances: {Class: object}
    + __call__(Class, ...): object
}
SingletonMetaclass -d-|> type

class NBPParser {
    - _data_source: Iterable
    + parse(): Generator[Tuple[str, str, Decimal, int]]
}

class XMLProvider {
    + xml: xml.ElementTree <<get>>
    + get_xml_gen(): Generator[ElementTree.Element]
}
XMLProvider -[dashed]-> "<<instantiates>>" SingletonMetaclass
XMLProvider --> NBPParser

class CurrencyCalculator {
    + currencies: [Currency] <<get>>
    + currencies_dict: {str: Currency} <<get>>
    + {static} convert(Currency, Currency, Decimal)
}
CurrencyCalculator -[dashed]-> XMLProvider
CurrencyCalculator -[dashed]--> NBPParser
CurrencyCalculator -[dashed]--> Currencies
CurrencyCalculator -l[dashed]-> Currency

class UserInterface {
    - _calculator: CurrencyCalculator
    + run(): void
}
UserInterface -[dashed]-> CurrencyCalculator

@enduml